# Form implementation generated from reading ui file 'time_is_website.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(645, 457)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 640, 455))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setObjectName("frame")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 0, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("color:red")
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.plainTextEdit.setTabChangesFocus(True)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(parent=self.frame)
        self.webEngineView.setGeometry(QtCore.QRect(0, 30, 641, 381))
        self.webEngineView.setUrl(QtCore.QUrl("https://time.is/Paris"))
        self.webEngineView.setObjectName("webEngineView")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(190, 420, 75, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 420, 75, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.plainTextEdit.setPlainText(_translate("Form", "点击Time.Is图标进行时间差计算"))
        self.pushButton.setText(_translate("Form", "reload"))
        self.pushButton_2.setText(_translate("Form", "close"))
from PyQt6 import QtWebEngineWidgets
