name: Test Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test PyInstaller build (no artifacts)
      run: |
        # Quick test build to verify everything works
        pyinstaller --onefile --console --name="BadmintonScript-Test" script_final_beta.py
        
        # Verify the exe was created
        if (Test-Path "dist/BadmintonScript-Test.exe") {
          Write-Host "✅ Test build successful!"
          $size = (Get-Item "dist/BadmintonScript-Test.exe").Length / 1MB
          Write-Host "📦 Executable size: $([math]::Round($size, 2)) MB"
        } else {
          Write-Host "❌ Test build failed!"
          exit 1
        }
        
    - name: Test import modules
      run: |
        python -c "
        try:
            from PyQt5.QtWidgets import QApplication
            from selenium import webdriver
            import requests
            print('✅ All modules imported successfully')
        except ImportError as e:
            print(f'❌ Import error: {e}')
            exit(1)
        "
